### ISSUE TITLE
Open respond links in the users preferred Mastodon client

### ISSUE THREAD

**Issue by jmjordan** [jmjordan/statuslog-ios#13]
If a respond link is a social.lol link, provide a way to open those types of links in an app of the users choosing.

Initial supported apps:
- Ivory (https://tapbots.com/support/ivory/tips/urlschemes)
- Mona (https://github.com/JunyuKuang/Spring-for-Twitter/blob/main/URL%20Schemes.md)

**Comment by maique** [comment]
Ice Cubes (https://github.com/Dimillian/IceCubesApp) has [icecubesapp://](icecubesapp://) working, but couldn’t find the documentation.

**Comment by maique** [comment]
New ones. Found out that mammoth:// and tusker:// work as well, but couldn't find any documentation as well.

- [Tusker](https://vaccor.space/tusker/), with code at [https://git.shadowfacts.net/shadowfacts/Tusker](https://git.shadowfacts.net/shadowfacts/Tusker)
- [Mammoth](https://getmammoth.app)

**Comment by jmjordan** [comment]
I made some progress on this last night as well. I added a setting that allows the user to change their default browser. I think that's where this setting will live

**Comment by maique** [comment]
Just saw the update with this feature (THANKS!), but can't find Mona in there... Sniffle... Sniffle...

**Comment by maique** [comment]
Thank you 😘
